### ISSUE TITLE
Videos Missing Code

### ISSUE THREAD

**Issue by bephrem1** [bephrem1/backtobackswe#1]
Balanced Parentheses: https://www.youtube.com/watch?v=CCyEXcNamC4
How To Permute A String: https://www.youtube.com/watch?v=GCm7m5671Ps
IP Address Decomposition: https://www.youtube.com/watch?v=KU7Ae2513h0
KMP Substring Search: https://www.youtube.com/watch?v=BXCEFAzhxGY
Test If A Binary Tree Is Symmetric: https://www.youtube.com/watch?v=XV7Sg2hJO3Q
Dutch National Flag Problem: https://www.youtube.com/watch?v=ER4ivZosqCg
0/1 Knapsack Problem: https://www.youtube.com/watch?v=xCbYmUPvc2Q
Depth First & Breadth First Graph Search: https://www.youtube.com/watch?v=TIbUeeksXcI
Reverse A Singly Linked List: https://www.youtube.com/watch?v=O0By4Zq0OFc
Middle of A Linked List: https://www.youtube.com/watch?v=UitXxwVeOrk
Compute All Mnemonics For A Phone Number: https://www.youtube.com/watch?v=a-sMgZ7HGW0
Reverse The Digits of An Integer: https://www.youtube.com/watch?v=ZQQoHr-2stA

**Comment by abhi-jha** [comment]
So, should I go ahead and implement these?

**Comment by bephrem1** [comment]
@abhi-jha Eh...yeah, go for it. I'll add the explanatory comments so don't worry about those...unless you do want to do them. Yeah, thank you very much.

**Comment by venkateshreddypala** [comment]
I'd like to write code for the Dutch National Flag Problem for this weekend any suggestions while writing the code?

**Comment by bephrem1** [comment]
@venkateshreddypala Sure. No suggestions, do ya thing.

**Comment by bephrem1** [comment]
Closing, stale
