### ISSUE TITLE
Bug in OnlineMedian.java

### ISSUE THREAD

**Issue by Gannys001** [bephrem1/backtobackswe#18]
At line 58, the new number should be pushed into lowerHalf when higherHalf is empty.

**Comment by chellitorvic** [comment]
But then it can result in NullPointerException at line 61 on the insertion of the next element, i.e. sequence [1, 2].

I've created pull request to address the issue #22

**Comment by bephrem1** [comment]
@chellitorvic Thanks, merged your pr
