### ISSUE TITLE
Not Needed for 

### ISSUE THREAD

**Issue by jackalsin** [bephrem1/backtobackswe#40]
https://github.com/bephrem1/backtobackswe/blob/2c66c302f266215876178ca5c72202925960d952/Sorting%2C%20Searching%2C%20%26%20Heaps/ImplementABinaryHeap/ImplementABinaryHeap.java#L191

```java
return  index != 0; 
```
Isn't it enough?

**Comment by BadrBelhiti** [comment]
I was thinking the same thing, but I'm sure it's just a precautionary measure.

**Comment by bephrem1** [comment]
Closing issue, this repository is no longer maintained. Thank you for pointing this out!
